language: python
python:
  - "2.7"
# command to install dependencies
before_install:
# Install miniconda to avoid compiling scipy
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda
install:
# # I copyed most of this from Theano rep
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then conda create --yes -q -n pyenv mkl python=2.6 numpy=1.6 scipy=0.11 nose=1.1 pyparsing=1.5 pip; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then conda create --yes -q -n pyenv mkl python=3.3 numpy=1.9.1 scipy=0.14.0 nose=1.3.4 pip; fi
    - source activate pyenv
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install pydot; fi
    - pip install . --no-deps --use-mirrors
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=top setup.py test
after_success:
    coveralls
