language: python
python:
  - "2.7"
# command to install dependencies
before_install:
# Install miniconda to avoid compiling scipy
   - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda/bin:$PATH
   - conda update --yes conda
   - git clone https://github.com/lisa-lab/pylearn2.git
   - export PYTHONPATH=$PWD/pylearn2
   - export PYLEARN2_DATA_PATH=$PWD   
install:
# # I copyed most of this from Theano rep
    - conda create --yes -q -n pyenv mkl python=2.7 numpy scipy theano nose pyparsing pip
    - source activate pyenv
    - python pylearn2/scripts/datasets/download_mnist.py
    - pip install pydot
    - pip install . --no-deps --use-mirrors
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=top setup.py test
after_success:
    coveralls
